### PR TITLE
VTC Marketing Funding

### PR DESCRIPTION
**Pull request by rmpuglet**
**Proposal**
Marketing is important in every aspect of the world. It enables businesses (and in this case the vertcoin community) to reach out to members in similar markets in order to increase awareness of themselves. Although the vertcoin community already contains many members, it is important that we continue to reach out to people already in the crypto space to make them aware of our project and how it works.

**Who is the target market?**
In all forms of marketing, the target market is one of the most important aspects. It is important that we correctly identify who we want to reach out to. With this marketing campaign, I am going to be targeting both miners and gamers, who may be interested in potentially mining or investing in Vertcoin. With the upcoming merge of Ethereum into Ethereum 2.0, Ethereum miners will be one of the main targets in this specific campaign. The aim will be to build awareness among the Ethereum community to increase the chances of them choosing Vertcoin when Ethereum swithces to PoS. This campaign will also spread awareness among the gaming community, as many PC gamers will not know how easy it is to mine Vertcoin in the background whilst gaming.

**When will the Campaign start?**
I am aiming to start the Campaign in mid July. The Ethereum merge will be occuring some time in August, so mid to late July will be the best time to spread awareness among the Ethereum Community. I started the fundraiser a month and a bit before this to give appropriate time to obtain funds for marketing.

**How will funds be spent?**
The funds will be spent solely on Marketing Campaigns on each of the platforms. I won't be taking any cut for setting up Marketing Campaigns. I will also be setting up accounts on various platforms and reaching out to target markets with these accounts. It is undecided where 40% of the funds will be spent as of yet, and this will be decided at the time based on the cheapest and most effective way to reach out to target markets.

**Thanks for your time.**
Thanks for reading this proposal, and I hope you will consider contributing a small proportion of your Vertcoin to aid the expansion of the community.

### CODE REVIEW

**Comment by KforG** [comment]
Am I correct in assuming that this will be an ad based campaign? 

Will the content of those ads only be text/existing images? Or will you also spend funds on video creation and similar, (This could in turn also be used as YouTube ads)?

**Comment by rmpuglet** [comment]
> Am I correct in assuming that this will be an ad based campaign?
> 
> Will the content of those ads only be text/existing images? Or will you also spend funds on video creation and similar, (This could in turn also be used as YouTube ads)?

I will mostly try to use existing images/existing videos as the content for ads. I could look at video creation, but it would be dependent on what the community wanted. However, for the advertising on twitter and reddit (where most crypto users can be found) i will stick mostly to image or existing video advertisements.

**Comment by vertiond** [comment]
I would suggest to break this down to a more specific goal targeting one platform at a time with a smaller funding amount.  You are responsible for selling your proposal to the community so I would post to reddit, discord, telegram etc. with specific examples of what this will entail as well as any previous work you have done and/or credentials of yours.

**Comment by rmpuglet** [comment]
> I would suggest to break this down to a more specific goal targeting one platform at a time with a smaller funding amount. 

I would be able to work with a smaller funding amount, but I didn't want to set a limit on it because the more raised, the more marketing I can do. I thought that 10,000 was a reasonable limit, but in reality, i would be able to work with any amount.

**Comment by rmpuglet** [comment]
> You are responsible for selling your proposal to the community so I would post to reddit, discord, telegram etc. with specific examples of what this will entail as well as any previous work you have done and/or credentials of yours.

I was also going wait until it got onto the funding page before I started sharing it to the community. Do I need to start promoting my idea before that or can I just wait for it to get onto there?

**Comment by vertiond** [comment]
Proposals that reach the funding stage have garnered community support in one way or another so that process begins now.  Judging by previous proposals that have took almost 6 months to raise 10000 VTC is the reason why I am suggesting to lower the amount.  Remember that you only are paid out when a milestone is completed which means that you are funding this yourself until then.

**Comment by vertiond** [comment]
CCS proposals are now taking place at https://github.com/vertcoin-project/ccs-proposals/ 
Feel free to open there if you still wish - this PR will now be closed.

**Pull request closed without merging**
